INSERT INTO USER_PROFILE(type) VALUES ('USER');
INSERT INTO USER_PROFILE(type) VALUES ('ADMIN');
INSERT INTO USER_PROFILE(type) VALUES ('XXX');
INSERT INTO APP_USER(sso_id, password, first_name, last_name, email, state) VALUES ('toannh','abc123', 'Toan','NH','toannh0401@gmail.com', 'Active');
INSERT INTO APP_USER(sso_id, password, first_name, last_name, email, state) VALUES ('rina001','abc124', 'Rina 1',' ','rina001@xyz.com', 'Active');
INSERT INTO APP_USER(sso_id, password, first_name, last_name, email, state) VALUES ('rina002','abc125', 'Rina 2',' ','rina002@xyz.com', 'Active');
INSERT INTO APP_USER(sso_id, password, first_name, last_name, email, state) VALUES ('rina003','abc126', 'Rina 3',' ','rina003@xyz.com', 'Active');
INSERT INTO APP_USER(sso_id, password, first_name, last_name, email, state) VALUES ('rina004','abc127', 'Rina 4',' ','rina004@xyz.com', 'Active');
INSERT INTO APP_USER_USER_PROFILE (user_id, user_profile_id) SELECT user.id, profile.id FROM app_user user, user_profile profile WHERE user.sso_id='toannh' and profile.type='USER';
INSERT INTO APP_USER_USER_PROFILE (user_id, user_profile_id) SELECT user.id, profile.id FROM app_user user, user_profile profile WHERE user.sso_id='rina001' and profile.type='USER';
INSERT INTO APP_USER_USER_PROFILE (user_id, user_profile_id) SELECT user.id, profile.id FROM app_user user, user_profile profile WHERE user.sso_id='rina002' and profile.type='ADMIN';
INSERT INTO APP_USER_USER_PROFILE (user_id, user_profile_id) SELECT user.id, profile.id FROM app_user user, user_profile profile WHERE user.sso_id='rina003' and profile.type='DBA';
INSERT INTO APP_USER_USER_PROFILE (user_id, user_profile_id) SELECT user.id, profile.id FROM app_user user, user_profile profile WHERE user.sso_id='toannh' and profile.type='ADMIN';
INSERT INTO APP_USER_USER_PROFILE (user_id, user_profile_id) SELECT user.id, profile.id FROM app_user user, user_profile profile WHERE user.sso_id='rina001' and profile.type='DBA';
INSERT INTO CATEGORY(id, name) VALUES('1', 'Danh mục quần áo');
INSERT INTO CATEGORY(id, name) VALUES('2', 'Quần áo nữ');
INSERT INTO CATEGORY(id, name) VALUES('3', 'Mới cập nhật');
INSERT INTO PRODUCT(id, categoryID, name, createTime, detail, user, discount, images) VALUES('P001', '1', 'xin chào các bạn thân mến', now(), 'detail 001', 'test', 10, 'https://media3.scdn.vn/img1/2016/3_6/532bf2_simg_c02915_720-720-19-0_cropf_simg_b5529c_250x250_maxb.jpg');
INSERT INTO PRODUCT(id, categoryID, name, createTime, detail, user, discount, images) VALUES('P002', '1', 'Product 002', now(), 'detail 002', 'test', 20, 'https://media3.scdn.vn/img1/2016/2_23/273c60_simg_b5529c_250x250_maxb.jpg');
INSERT INTO PRODUCT(id, categoryID, name, createTime, detail, user, discount, images) VALUES('P003', '1', 'Product 003', now(), 'detail 003', 'test', 10, 'https://media3.scdn.vn/img1/2016/3_6/532bf2_simg_c02915_720-720-19-0_cropf_simg_b5529c_250x250_maxb.jpg');
INSERT INTO PRODUCT(id, categoryID, name, createTime, detail, user, discount, images) VALUES('P004', '2', 'Product 004', now(), 'detail 004', 'test', 0, 'https://media3.scdn.vn/img1/2015/8_14/e36559_simg_b5529c_250x250_maxb.jpg');
INSERT INTO PRODUCT(id, categoryID, name, createTime, detail, user, discount, images) VALUES('P005', '2', 'Product 005', now(), 'detail 005', 'test', 15, 'https://media3.scdn.vn/img1/2015/8_14/10fa77_simg_b5529c_250x250_maxb.jpg');
INSERT INTO PRODUCT(id, categoryID, name, createTime, detail, user, discount, images) VALUES('P006', '2', 'Product 006', now(), 'detail 006', 'test', 25, 'https://media3.scdn.vn/img1/2015/8_14/10fa77_simg_b5529c_250x250_maxb.jpg');
INSERT INTO PRODUCT(id, categoryID, name, createTime, detail, user, discount, images) VALUES('P007', '3', 'Product 007', now(), 'detail 007', 'test', 22, 'https://media3.scdn.vn/img1/2015/8_14/10fa77_simg_b5529c_250x250_maxb.jpg');